version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Ecommerce
    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    
